name: 新規リリース(Pull Request)を作成する

on:
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Bump version
        run: |
          get_defined_versions () {
            grep -o -P "(?<=ThisBuild / version := \")\d+(?=\")" build.sbt
          }

          update_version_to () {
            echo "置換先のバージョン： $1"
            sed -E "s/ThisBuild \/ version := \"[0-9]+\"/ThisBuild \/ version := \"$1\"/g" build.sbt
          }

          if [ ! $(get_defined_versions | wc -l) = "1" ]; then
            echo "エラー：build.sbt でのバージョン指定が一意でありません。"
            exit 1
          fi

          update_version_to $(get_defined_versions | xargs expr 1 +)
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  merge_master:
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - uses: actions/checkout@master

  create_pr:
    runs-on: ubuntu-latest
    needs: create_pr
    steps:
      - uses: actions/checkout@master
